const BAD_REQUEST_ERROR = 400;
const INTERNAL_SERVER_ERROR = 500;
const NOT_FOUND_ERROR = 404;
const EMAIL_CONFLICT = 409;
const NOT_AUTHORIZATION = 401;
const FORBIDDEN = 403;

module.exports = {
  BAD_REQUEST_ERROR,
  INTERNAL_SERVER_ERROR,
  NOT_FOUND_ERROR,
  EMAIL_CONFLICT,
  NOT_AUTHORIZATION,
  FORBIDDEN,
};
